// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dPVhjxWdErsi2Yh7w74TNkP19VZX_zo',
    appId: '1:339334159762:web:c207404ec3ff89cfbb754b',
    messagingSenderId: '339334159762',
    projectId: 'smu-soft',
    authDomain: 'smu-soft.firebaseapp.com',
    storageBucket: 'smu-soft.appspot.com',
    measurementId: 'G-EVP03L987B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbZaFQUHLdoxQV_JLFjMyXmr7V_dSpUQ',
    appId: '1:339334159762:android:b3a6f89eed62e5d6bb754b',
    messagingSenderId: '339334159762',
    projectId: 'smu-soft',
    storageBucket: 'smu-soft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnSgwmb8REeSsdLzCgHF3aXz_U71jCjfE',
    appId: '1:339334159762:ios:f75d5a30b0820de1bb754b',
    messagingSenderId: '339334159762',
    projectId: 'smu-soft',
    storageBucket: 'smu-soft.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnSgwmb8REeSsdLzCgHF3aXz_U71jCjfE',
    appId: '1:339334159762:ios:d90d695897aca347bb754b',
    messagingSenderId: '339334159762',
    projectId: 'smu-soft',
    storageBucket: 'smu-soft.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
